<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>nes mouse</AssemblyName>
    <RootNamespace>nes_mouse</RootNamespace>
    <ApplicationIcon>Resources\this.Icon.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.DirectInput" Version="3.6.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\this.Icon.ico" />
  </ItemGroup>

</Project>
