<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NESMouse.Core\NESMouse.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ppy.SDL2-CS" Version="1.0.741-alpha" />
  </ItemGroup>

</Project>
